# Site settings
name: Primordial Analytics
title: Primordial Analytics
tagline: "AI-focused Analytics"
email: contact@primordialanalytics.com
description: "Primordial Analytics is an AI-focused consultancy."
blogurl: "/blog/"
baseurl: ""
url: https://www.primordialanalytics.com
permalink: pretty
markdown: kramdown
highlighter: rouge

# add collections
collections:
  team:
  casestudies:
  posts:
    output: true
    permalink: /blog/:title/

# add other dirs
includes:
- vendor
- favicons
- fonts
- img
- js

# exclude other dirs
exclude:
- node_modules
- gulpfile.js
- gulpfile_example.js
- README.md
- svg
- .idea

# Social networks usernames
social:
  - icon: fab fa-twitter
    url: https://twitter.com/primordialytics
  - icon: fab fa-facebook-f
    url: https://fb.me/primordialytics
  - icon: fab fa-linkedin-in
    url: https://linkedin.com/company/primordial-analytics/
  - icon: fab fa-github-alt
    url: https://github.com/primordial-analytics

# Postal address
address:
  - line: Technology Drive
  - line: Knoxville, TN 37932
